# Generated by Django 5.0.7 on 2024-11-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_item_remove_order_items_alter_order_status_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
