# Generated by Django 5.0.7 on 2024-11-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
