# Generated by Django 5.0.7 on 2024-11-01 18:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_item_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="count",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="order.item",
            ),
        ),
    ]
