# Generated by Django 5.0.7 on 2024-11-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_alter_orderitem_count_alter_orderitem_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
